### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by rachidelaid** [tbvjaos510/electron-disable-minimize#1]
`> node-gyp rebuild

make: Entering directory '/home/rachid/Desktop/kilper/node_modules/electron-disable-minimize/build'
  CXX(target) Release/obj.target/disable-minimize/lib.o
../lib.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE DisableMinimize(Nan::NAN_METHOD_ARGS_TYPE)’:
../lib.cc:22:5: error: ‘HWND’ was not declared in this scope
     HWND hwnd = NULL;
     ^~~~
../lib.cc:37:5: error: ‘hwnd’ was not declared in this scope
     hwnd = (HWND)handle;
     ^~~~
../lib.cc:37:5: note: suggested alternative: ‘rand’
     hwnd = (HWND)handle;
     ^~~~
     rand
../lib.cc:40:10: error: expected ‘;’ before ‘nWinHandle’
     HWND nWinHandle = FindWindowEx(NULL, NULL, "Progman", NULL);
          ^~~~~~~~~~
../lib.cc:41:5: error: ‘nWinHandle’ was not declared in this scope
     nWinHandle = FindWindowEx(nWinHandle, NULL, "SHELLDLL_DefView", NULL);
     ^~~~~~~~~~
../lib.cc:41:5: note: suggested alternative: ‘handle’
     nWinHandle = FindWindowEx(nWinHandle, NULL, "SHELLDLL_DefView", NULL);
     ^~~~~~~~~~
     handle
../lib.cc:41:18: error: ‘FindWindowEx’ was not declared in this scope
     nWinHandle = FindWindowEx(nWinHandle, NULL, "SHELLDLL_DefView", NULL);
                  ^~~~~~~~~~~~
../lib.cc:46:37: error: ‘LONG_PTR’ was not declared in this scope
         SetWindowLongPtr(hwnd, -8, (LONG_PTR)nWinHandle);
                                     ^~~~~~~~
../lib.cc:46:37: note: suggested alternative: ‘LONG_MAX’
         SetWindowLongPtr(hwnd, -8, (LONG_PTR)nWinHandle);
                                     ^~~~~~~~
                                     LONG_MAX
../lib.cc:46:9: error: ‘SetWindowLongPtr’ was not declared in this scope
         SetWindowLongPtr(hwnd, -8, (LONG_PTR)nWinHandle);
         ^~~~~~~~~~~~~~~~
../lib.cc:36:19: warning: unused variable ‘handle’ [-Wunused-variable]
     unsigned long handle = *reinterpret_cast<unsigned long *>(bufferData);
                   ^~~~~~
disable-minimize.target.mk:101: recipe for target 'Release/obj.target/disable-minimize/lib.o' failed
make: *** [Release/obj.target/disable-minimize/lib.o] Error 1
make: Leaving directory '/home/rachid/Desktop/kilper/node_modules/electron-disable-minimize/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rachid/Desktop/kilper/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.3.0-26-generic
gyp ERR! command "/usr/bin/node" "/home/rachid/Desktop/kilper/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/rachid/Desktop/kilper/node_modules/electron-disable-minimize
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! Linux 5.3.0-26-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "electron-disable-minimize"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! electron-disable-minimize@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-disable-minimize@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-disable-minimize package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-disable-minimize
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-disable-minimize
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rachid/Desktop/kilper/npm-debug.log
`

**Comment by tbvjaos510** [comment]
Thank you for issue! It will help to fix if you let me know your OS.

**Comment by rachidelaid** [comment]
I'm using ubuntu right now.
but I have tried it in windows 10 but the same error.

**Comment by tbvjaos510** [comment]
@rachidelaid I updated v2.0.0 to fix build error. Please upgrade module version. Thanks!

**Comment by rachidelaid** [comment]
okay I will try it right now thank you

**Comment by rachidelaid** [comment]
it worked thank you.
but it returns false and I can still minimize the app
can you please help me fix that?

**Comment by tbvjaos510** [comment]
This module only works on windows. Other platform not working current.. If found native code for disable minimize in mac and linux, I will support them. Thanks!

**Comment by tbvjaos510** [comment]
@rachidelaid can i close issue?

**Comment by rachidelaid** [comment]
did you manage to support the other platforms?
